/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
package ShelterPages;

import javax.swing.JFrame;
=======
package HospitalPage;
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java

/**
 *
 * @author iris
 */
<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
public class PetInformationPage extends javax.swing.JFrame {

    /**
     * Creates new form PetInformationPage
     */
    public PetInformationPage() {
=======
public class NutriRecipe extends javax.swing.JFrame {

    /**
     * Creates new form NutriRecipe
     */
    public NutriRecipe() {
        initComponents();
    }
    
    public NutriRecipe(int id, String uname, String role) {
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
        jbtnappoinment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnappoinment.setText("Make an Appoinatment");
        jbtnappoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnappoinmentActionPerformed(evt);
            }
        });
=======
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Review Food Recipe");
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
                .addContainerGap()
                .addComponent(jbtnappoinment)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addComponent(jbtnappoinment)
                .addGap(30, 30, 30))
=======
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(392, Short.MAX_VALUE))
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnappoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnappoinmentActionPerformed
        // TODO add your handling code here:
        AdoptorInformationPage adpinfo = new AdoptorInformationPage();
        adpinfo.setVisible(true);
    }//GEN-LAST:event_jbtnappoinmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
            java.util.logging.Logger.getLogger(PetInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
=======
            java.util.logging.Logger.getLogger(NutriRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NutriRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NutriRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NutriRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
                new PetInformationPage().setVisible(true);
=======
                new NutriRecipe().setVisible(true);
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD:src/ShelterPages/PetInformationPage.java
    private javax.swing.JButton jbtnappoinment;
=======
    private javax.swing.JLabel jLabel1;
>>>>>>> bbf7e3348909c4db5e7b6b51fb6c3f4148b47547:src/HospitalPage/NutriRecipe.java
    // End of variables declaration//GEN-END:variables
}
