/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ShelterPages;


import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author pkuhore
 */
public class VolunteerPage extends javax.swing.JFrame {

    /**
     * Creates new form VolunteerPage
     */
    
    String gender;
    String spay;
    String disabled;
    String vaccination;
    String filename = null;
    byte[] strayanimals_image = null;
    
    
    public VolunteerPage() {
        initComponents();
        show_strayanimals();
    }
    
    public ArrayList<StrayAnimals> strayanimalsList(){
        ArrayList<StrayAnimals> strayanimalsList = new ArrayList<>();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/petcommunity", "root", "");
            String query1 = "SELECT * FROM strayanimals";
            Statement st = con.createStatement();
            ResultSet rs =st.executeQuery(query1);
            
            StrayAnimals strayanimals;
            
            while(rs.next()){
            
                strayanimals = new StrayAnimals(rs.getInt("sno"),rs.getString("name"),rs.getString("gender"),rs.getInt("age"),rs.getDate("time_arrive"),rs.getString("spay"),rs.getString("disabled"),rs.getString("vaccination"),rs.getString("pettype"),rs.getBytes("images"));
                strayanimalsList.add(strayanimals);
            
            }
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        System.out.println(strayanimalsList);
        return strayanimalsList;
        
    }
    
    public void show_strayanimals(){
    
        ArrayList<StrayAnimals> list = strayanimalsList();
        DefaultTableModel model = (DefaultTableModel)jtb_display_strayanimals.getModel();
        Object[] row = new Object[9];
        for (int i=0; i<list.size();i++){
        
            row[0] = list.get(i).getSno();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getGender();
            row[3] = list.get(i).getAge();
            row[4] = list.get(i).getTime_Arrive();
            row[5] = list.get(i).getSpay();
            row[6] = list.get(i).getDisabled();
            row[7] = list.get(i).getVaccination();
            row[8]= list.get(i).getPettype();
            model.addRow(row);
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlblname = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jlblgender = new javax.swing.JLabel();
        jbtnfemale = new javax.swing.JRadioButton();
        jbtnmale = new javax.swing.JRadioButton();
        jlblage = new javax.swing.JLabel();
        jtxtage = new javax.swing.JTextField();
        jlbltimearrive = new javax.swing.JLabel();
        jdctimearrive = new com.toedter.calendar.JDateChooser();
        jlblspay = new javax.swing.JLabel();
        jbtnyes = new javax.swing.JRadioButton();
        jbtnno = new javax.swing.JRadioButton();
        jlbldisabled = new javax.swing.JLabel();
        jbtndyes = new javax.swing.JRadioButton();
        jbtndno = new javax.swing.JRadioButton();
        jlblvacci = new javax.swing.JLabel();
        jbtnvyes = new javax.swing.JRadioButton();
        jbtnvno = new javax.swing.JRadioButton();
        jlblpettype = new javax.swing.JLabel();
        jtxtpettype = new javax.swing.JTextField();
        jbtnsave = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_display_strayanimals = new javax.swing.JTable();
        jbtnupdate = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jlblimage = new javax.swing.JLabel();
        jbtnimage = new javax.swing.JButton();
        jbtnsearch = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblname.setText("Name :");

        jlblgender.setText("Gender :");

        buttonGroup1.add(jbtnfemale);
        jbtnfemale.setText("Female");

        buttonGroup1.add(jbtnmale);
        jbtnmale.setText("Male");

        jlblage.setText("Estimate Age :");

        jlbltimearrive.setText("Time arrive Shelter :");

        jlblspay.setText("Spay :");

        buttonGroup2.add(jbtnyes);
        jbtnyes.setText("Yes");

        buttonGroup2.add(jbtnno);
        jbtnno.setText("No");

        jlbldisabled.setText("Disabled:");

        buttonGroup3.add(jbtndyes);
        jbtndyes.setText("Yes");

        buttonGroup3.add(jbtndno);
        jbtndno.setText("No");

        jlblvacci.setText("Vaccination :");

        buttonGroup4.add(jbtnvyes);
        jbtnvyes.setText("Yes");

        buttonGroup4.add(jbtnvno);
        jbtnvno.setText("No");

        jlblpettype.setText("Pet Type :");

        jbtnsave.setText("Save");
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });

        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });

        jtb_display_strayanimals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Name", "Gender", "Age", "TimeArrive", "Spay", "Disabled", "Vaccination", "Pettype"
            }
        ));
        jtb_display_strayanimals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_display_strayanimalsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_display_strayanimals);

        jbtnupdate.setText("Update");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });

        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });

        jbtnimage.setText("Browse");
        jbtnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimageActionPerformed(evt);
            }
        });

        jbtnsearch.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblname)
                                        .addComponent(jlblgender))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jbtnfemale)
                                            .addGap(18, 18, 18)
                                            .addComponent(jbtnmale))
                                        .addComponent(jtxtname)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlblpettype, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jlblage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jlblspay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlbltimearrive)
                                                        .addComponent(jlbldisabled, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlblvacci))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addComponent(jbtnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtage)
                                        .addComponent(jdctimearrive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jbtnyes)
                                                .addComponent(jbtndyes)
                                                .addComponent(jbtnvyes))
                                            .addGap(39, 39, 39)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jbtnvno)
                                                .addComponent(jbtndno)
                                                .addComponent(jbtnno))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jtxtpettype))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jlblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jtxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jbtnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblname))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblgender)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtnfemale)
                                .addComponent(jbtnmale)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblage)
                            .addComponent(jtxtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbltimearrive)
                            .addComponent(jdctimearrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblspay)
                            .addComponent(jbtnyes)
                            .addComponent(jbtnno))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbldisabled)
                            .addComponent(jbtndyes)
                            .addComponent(jbtndno))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblvacci)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtnvyes)
                                .addComponent(jbtnvno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblpettype)
                            .addComponent(jtxtpettype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jlblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jbtnimage))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnsearch)
                            .addComponent(jtxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnsave)
                    .addComponent(jbtnupdate)
                    .addComponent(jbtndelete)
                    .addComponent(jbtnreset))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String time_arrive = dateformat.format(jdctimearrive.getDate());
        

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/petcommunity", "root", ""); 
            String query = "insert into strayanimals(name,gender,age,time_arrive,spay,disabled,vaccination,pettype,images)values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, jtxtname.getText());
            if(jbtnfemale.isSelected()){
                gender = "Female";
            }
            if(jbtnmale.isSelected()){
                gender = "Male";
            }
            pst.setString(2, gender);
            pst.setInt(3,Integer.parseInt(jtxtage.getText()));  //这里的数据验证要判断integer
            
            pst.setString(4, time_arrive);
            
            if(jbtnyes.isSelected()){
                spay = "Yes";
            }
            if(jbtnno.isSelected()){
                spay = "No";
            }
            pst.setString(5, spay);
            
            if(jbtndyes.isSelected()){
                disabled = "Yes";
            }
            if(jbtndno.isSelected()){
                disabled = "No";
            }
            pst.setString(6, disabled);
            
            if(jbtnvyes.isSelected()){
                vaccination = "Yes";
            }
            if(jbtnvno.isSelected()){
                vaccination = "No";
            }
            pst.setString(7,vaccination);
            
            pst.setString(8,jtxtpettype.getText());
            
            pst.setBytes(9,strayanimals_image);
            
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jtb_display_strayanimals.getModel();
            model.setRowCount(0);
            show_strayanimals();
            JOptionPane.showMessageDialog(null, "Inserted Successfully!");
            
            
            
            
        }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnsaveActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        try {
            // TODO add your handling code here:
            jtxtname.setText("");
            buttonGroup1.clearSelection();
            jtxtage.setText("");
            
            String dateValue ="1900-10-10";
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            jdctimearrive.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(VolunteerPage.class.getName()).log(Level.SEVERE, null, ex);
        }
             buttonGroup2.clearSelection();
             buttonGroup3.clearSelection();
             buttonGroup4.clearSelection();
             jtxtpettype.setText("");
             jlblimage.setIcon(null);
        
        
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jtb_display_strayanimalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_display_strayanimalsMouseClicked
        // TODO add your handling code here:
        int i = jtb_display_strayanimals.getSelectedRow();
        TableModel model = jtb_display_strayanimals.getModel();
        jtxtname.setText(model.getValueAt(i,1).toString());
        String sex = model.getValueAt(i, 2).toString();
            if (sex.equals("Female")){
            
                jbtnfemale.setSelected(true);
                
            }
            else{
            
                jbtnmale.setSelected(true);
            
            }
        jtxtage.setText(model.getValueAt(i, 3).toString());
        
        String dateValue2 =model.getValueAt(i, 4).toString();
        Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue2);
        } catch (ParseException ex) {
            Logger.getLogger(VolunteerPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        jdctimearrive.setDate(date);
        
        String spayy = model.getValueAt(i, 5).toString();
            if (spayy.equals("Yes")){
            
                jbtnyes.setSelected(true);
                
            }
            else{
            
                jbtnno.setSelected(true);
            
            }
        String disabledd = model.getValueAt(i, 6).toString();
            if (disabledd.equals("Yes")){
            
                jbtndyes.setSelected(true);
                
            }
            else{
            
                jbtndno.setSelected(true);
            
            }
        String vaccinationn = model.getValueAt(i, 7).toString();
            if (vaccinationn.equals("Yes")){
            
                jbtnvyes.setSelected(true);
                
            }
            else{
            
                jbtnvno.setSelected(true);
            
            }
        jtxtpettype.setText(model.getValueAt(i, 8).toString());
        byte[] img = (strayanimalsList().get(i).getPicture());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(jlblimage.getWidth(),jlblimage.getHeight(),Image.SCALE_SMOOTH));
        jlblimage.setIcon(imageIcon);
    }//GEN-LAST:event_jtb_display_strayanimalsMouseClicked

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String time_arrive = dateformat.format(jdctimearrive.getDate());

        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/petcommunity", "root", "");
            int row = jtb_display_strayanimals.getSelectedRow();
            String value = (jtb_display_strayanimals.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE strayanimals SET name = ?,gender=?,age=?,time_arrive=?,spay=?,disabled=?,vaccination=?,pettype=? ,images = ? where sno="+value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, jtxtname.getText());
            if(jbtnfemale.isSelected()){
                gender = "Female";
            }
            if(jbtnmale.isSelected()){
                gender = "Male";
            }
            pst.setString(2, gender);
            pst.setInt(3,Integer.parseInt(jtxtage.getText()));  //这里的数据验证要判断integer
            
            pst.setString(4, time_arrive);
            
            if(jbtnyes.isSelected()){
                spay = "Yes";
            }
            if(jbtnno.isSelected()){
                spay = "No";
            }
            pst.setString(5, spay);
            
            if(jbtndyes.isSelected()){
                disabled = "Yes";
            }
            if(jbtndno.isSelected()){
                disabled = "No";
            }
            pst.setString(6, disabled);
            
            if(jbtnvyes.isSelected()){
                vaccination = "Yes";
            }
            if(jbtnvno.isSelected()){
                vaccination = "No";
            }
            pst.setString(7,vaccination);
            
            pst.setString(8,jtxtpettype.getText());
            
            pst.setBytes(9,strayanimals_image);
            
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jtb_display_strayanimals.getModel();
            model.setRowCount(0);
            show_strayanimals();
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete it ?", "Delete",JOptionPane.YES_NO_OPTION);
        if(opt==0){
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/petcommunity", "root", "");
            int row = jtb_display_strayanimals.getSelectedRow();
            String value = (jtb_display_strayanimals.getModel().getValueAt(row, 0).toString());
            String query = "DELETE FROM strayanimals where sno="+value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jtb_display_strayanimals.getModel();
            model.setRowCount(0);
            show_strayanimals();
            JOptionPane.showMessageDialog(null, "Deleted Successfully!");
         }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jbtnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimageActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jlblimage.getWidth(),jlblimage.getHeight(),Image.SCALE_SMOOTH));
        jlblimage.setIcon(imageIcon);
        
        try{
        
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf))!=-1;){
            
                bos.write(buf,0,readNum);
            
            }
            strayanimals_image = bos.toByteArray();
        
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null,e);
        
        }
    }//GEN-LAST:event_jbtnimageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolunteerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolunteerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolunteerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolunteerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolunteerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JRadioButton jbtndno;
    private javax.swing.JRadioButton jbtndyes;
    private javax.swing.JRadioButton jbtnfemale;
    private javax.swing.JButton jbtnimage;
    private javax.swing.JRadioButton jbtnmale;
    private javax.swing.JRadioButton jbtnno;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JRadioButton jbtnvno;
    private javax.swing.JRadioButton jbtnvyes;
    private javax.swing.JRadioButton jbtnyes;
    private com.toedter.calendar.JDateChooser jdctimearrive;
    private javax.swing.JLabel jlblage;
    private javax.swing.JLabel jlbldisabled;
    private javax.swing.JLabel jlblgender;
    private javax.swing.JLabel jlblimage;
    private javax.swing.JLabel jlblname;
    private javax.swing.JLabel jlblpettype;
    private javax.swing.JLabel jlblspay;
    private javax.swing.JLabel jlbltimearrive;
    private javax.swing.JLabel jlblvacci;
    private javax.swing.JTable jtb_display_strayanimals;
    private javax.swing.JTextField jtxtage;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtpettype;
    private javax.swing.JTextField jtxtsearch;
    // End of variables declaration//GEN-END:variables
}
